image: Visual Studio 2017
configuration: Release
platform:
  - x64

init:
  - set PATH=%PATH%;C:\Qt\5.9.2\msvc2017_64\bin

before_build:
  - cmake -G "Visual Studio 15 2017 Win64" -DWITH_TESTS=ON -DCMAKE_BUILD_TYPE=Release .

build:
  project: ALL_BUILD.vcxproj

test:
  - msbuild RUN_TESTS.vcxproj

branches:
  only:
  - master