image: Visual Studio 2017
configuration: Release
platform:
  - x64

init:
  - set MYSQL_LIB="C:\Program Files\MySQL\MySQL Server 5.7\lib"
  - set PATH=%PATH%;C:\Qt\5.9.2\msvc2017_64\bin;%MYSQL_LIB%

before_build:
  - cmake -G "Visual Studio 15 2017 Win64" -DWITH_TESTS=ON -DCMAKE_BUILD_TYPE=Release .

build:
  project: ALL_BUILD.vcxproj

after_build:
  - msbuild RUN_TESTS.vcxproj

branches:
  only:
  - master