image: Visual Studio 2017
configuration: Release
platform:
  - x64

before_build:
  - ps: mkdir build
  - cd build
  - cmake -G "Visual Studio 15 2017 Win64" -DWITH_TESTS=ON -DCMAKE_BUILD_TYPE=Release ../

build:
  project: RUN_TESTS.vcxproj

branches:
  only:
  - master