# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: buildpack-deps:zesty

    working_directory: ~/repo

    steps:
      - checkout
      - run: apt-get update -y
      - run: apt-get install locales locales-all cmake qt5-default libqt5websockets5 libqt5websockets5-dev libqt5sql5-mysql -y
      - run: update-locale LANG=en_US.UTF-8
      - run: cmake -DWITH_TESTS=ON -DCMAKE_BUILD_TYPE=Release .
      - run: make -j4
      - run: ctest --verbose
